server:
  port: 9000

spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
  datasource:
    url: jdbc:mysql://localhost:3306/accounts_db
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
